added assume role functionality and updated the documentation

diff --git a/bin/k8comp b/bin/k8comp
--- a/bin/k8comp
+++ b/bin/k8comp
@@ -1,6 +1,6 @@
 #!/bin/bash
 set +x
-version=0.6.1
+version=0.6.2-beta1
 
 if [ -z ${k8comp_dir} ]
 then
@@ -16,7 +16,7 @@ auto_git_pull=false #git pull before each deployment
 main_deployment_branch=master #works in conjunction with `k8comp_environment`
 projects_repo= #works in conjunction with `auto_git_pull`
 hieradata_repo= #works in conjunction with `auto_git_pull`
-aws_sm_prefix=AWSSM
+aws_sm_prefix=AWSSM #the prefix for the AWS Secrets Manager variables
 
 # Added option to load k8comp.conf dynamically
 if [ -f ${k8comp_dir}/k8comp.conf ]
@@ -149,6 +149,9 @@ usage() {
                                          For pulling via ssh make sure the private key is available
                                          on the server/container.
 
+ --profile | -arp | -aarp                Specify the AWS IAM profile to be used for AWS Secrets manager
+                                         secrets retrieval
+
  Examples:
   k8comp pull
   k8comp pull -b test_branch
@@ -163,6 +166,8 @@ usage() {
 
   k8comp -t ingress -a application -e environment
   k8comp -t redirects/ingress -a application -e environment
+
+  k8comp -p project -a application -e environment --profile development
 
   k8comp -p project -a application -e development -x var1=value1 -x var2=value2 | kubectl create -f -
   k8comp -p project -a application -x var1=value1 -x var2=value2 | kubectl apply -f -
@@ -268,6 +273,12 @@ while [ $# -gt 0 ]; do
                 shift
             fi
             ;;
+        -aarp|-arp|--aws-assume-role-profile|--profile|-profile)
+            if [ -n "$2" ]; then
+                aws_assume_role_profile="--profile ${2}"
+                shift
+            fi
+            ;;
         -x|--xtra|xtra)
             read_x_args "${@:2}"
             ;;
@@ -312,7 +323,7 @@ aws_sm_function () {
     nv2=${nv%?}
     nv3=${nv2##*BASE64,}
     nv4=${nv3%%:*}
-    aws_sm_secret=$(aws secretsmanager get-secret-value --query SecretString --secret-id $nv4 --version-stage AWSCURRENT --output text)
+    aws_sm_secret=$(aws secretsmanager get-secret-value ${aws_assume_role_profile} --query SecretString --secret-id $nv4 --version-stage AWSCURRENT --output text)
 
     if [[ "${nv2}" =~ ":" ]]
     then
@@ -568,6 +579,19 @@ wq
 __EOF__
 }
 
+check_var_fail_safe () {
+  nf_var+="$1 "
+  if [ "$var_fail_safe" == "true" ]
+  then
+      error "${variable%% default *} not found in hiera"
+      clean
+      exit 1
+  else
+      # avoid nil value being added on the deployment file
+      sed -i "s|%{${variable}}||g" ${tmp_file}
+  fi
+}
+
 replace_allvar() {
     # set a different IFS in case the default variables have white spaces
     OLDIFS=$IFS
@@ -588,10 +612,9 @@ replace_allvar() {
         if [[ "$($hr)" =~ "${aws_sm_prefix}" ]]
         then
           aws_var=$(aws_sm_function "$($hr)")
-          if [ "${aws_var}" = "" ]
+          if [ "${aws_var}" = "" ] || [ "$aws_var" = "Cg==" ]
           then
-            nf_var+="$($hr) "
-            sed -i "s|%{${variable}}||g" ${tmp_file}
+            check_var_fail_safe "$($hr) "
           else
            sed -i "s|%{${variable}}|${aws_var}|g" ${tmp_file}
           fi
@@ -601,24 +624,14 @@ replace_allvar() {
             aws_var=$(aws_sm_function "$variable")
             if [ "${aws_var}" = "" ] || [ "$aws_var" = "Cg==" ]
             then
-              nf_var+="$variable "
-              sed -i "s|%{${variable}}||g" ${tmp_file}
+              check_var_fail_safe "${variable} "
             else
              sed -i -e "s|%{${variable}}|${aws_var}|g" ${tmp_file}
             fi
         # if hiera variable is not found and no default value is set in the template add the variable in the final message with variables not found
         elif [ "$($hr)" = "nil" ] || [ -z "$($hr)" ] && [[ "${variable%% default *}" == "${variable##* default }" ]] && [[ ! "$($hr)" =~ "${aws_sm_prefix}" ]]
         then
-            nf_var+="${variable%% default *} "
-            if [ "$var_fail_safe" == "true" ]
-            then
-                error "${variable%% default *} not found in hiera"
-                clean
-                exit 1
-            else
-                # avoid nil value being added on the deployment file
-                sed -i "s|%{${variable}}||g" ${tmp_file}
-            fi
+          check_var_fail_safe "${variable%% default *} "
             # if variable has more lines
         elif [[ "$($hr)" =~ '=>' ]]
         then
