created new nierarchy example, added kube-system files, major changes to allow multiple deployment files.

diff --git a/k8comp b/k8comp
--- a/k8comp
+++ b/k8comp
@@ -1,40 +1,52 @@
 #!/bin/bash
 
 source /opt/k8comp/k8comp.conf
+source /opt/k8comp/usage
 
 programname=$0
+red="$(tput setaf 1)"
+green="$(tput setaf 2)"
+yellow="$(tput setaf 3)"
 
-usage() {
-  echo -e "\n\x1b[32m Usage: $programname [-h | -p <project_name> -a <application> -e <environment> ] \x1b[0m"
-  echo -e "\x1b[32m  -h | --help :                           Display usage information. \x1b[0m"
-  echo -e "\x1b[32m  -p | --project <project_name> :         Project name as specified on the projects folder. Configuration specified in k8comp.conf. Current path ${projects_path} \x1b[0m"
-  echo -e "\x1b[32m  -a | --application <application> :      The name of the application which need to be deployed. ${projects_path}/<project>/<application>/<application>.yaml \x1b[0m"
-  echo -e "\x1b[32m  -e | --environment <environment> :      The environment will be checked from hiera. If no values are found in hiera the variables will not be replaced. \x1b[0m"
-  echo -e "\x1b[32m  -x | --xtra <variable> :                The variable specified on the cmd run it will be used to update a value on the final yaml file. This will have priority over hiera value. Is not mandatory to be specified. The format is variable=value \x1b[0m"
-  echo -e "\n\x1b[32m Example:
-
-  k8comp -p project1 -a app1 -e development | kubectl create -f -
-  k8comp -p project1 -a app1 -e development | kubectl apply -f -
-
-  k8comp -p project1 -a app1 -e development -x var1=value1 -x var2=value2 | kubectl create -f -
-  k8comp -p project1 -a app1 -e development -x var1=value1 -x var2=value2 | kubectl apply -f -
-
-  Dry run:
-
-  k8comp -p project1 -a app1 -e development
-  k8comp -p project1 -a app1 -e development -x var1=value1\x1b[0m\n"
+MAIN() {
+  check_vars
+  set_file
+  create_tmp
+  replace_var
+  replace_xvar
+  replace_allvar
+  print_file
+  clean
 }
 
-read_x_args()
-{
-    while (($#)) && [[ $1 != -* ]]; do args+=("$1"); shift; done
+error() {
+    echo -e "${red}[ ERROR ] - $@ $(tput sgr0)"
+}
+
+message_green() {
+    echo -e "${green} $@ $(tput sgr0)"
+}
+
+message_yellow() {
+    echo -e "${yellow} $@ $(tput sgr0)"
+}
+
+read_x_args() {
+  while (($#)) && [[ $1 != -* ]];
+  do args+=("$1");
+    shift;
+  done
 }
 
 while [ $# -gt 0 ]; do
+# set the variable from input for all the arguments
+  input+=("$1")
+# set variables from input
   case "$1" in
     -p|--project)
       if [ -n "$2" ]; then
         project=$2
+        hrp="project=$2"
         shift
       else
         usage
@@ -44,6 +56,7 @@ while [ $# -gt 0 ]; do
     -a|--application)
       if [ -n "$2" ]; then
         application=$2
+        hra="application=$2"
         shift
       else
         usage
@@ -53,10 +66,8 @@ while [ $# -gt 0 ]; do
     -e|--environment)
       if [ -n "$2" ]; then
         environment=$2
+        hre="environment=$2"
         shift
-      else
-        usage
-        exit 1
       fi
     ;;
     -x|--xtra)
@@ -70,55 +81,107 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-# Define the location of the locations
-deployments=${k8comp_home}/deployments/${project}/${application}-${environment}/${application}-`date +%Y-%m-%d-%H-%M-%S`
-
-# Location of the most current deployment/test
-latest_deployment=${k8comp_home}/deployments/${project}/${application}-${environment}/latest
-
 # check if the required values are declared
-if [ -z ${environment} ] || [ -z ${application} ] || [ -z ${project} ]
-	then
-	usage
-	exit 1
-fi
-
-# check if the default yaml file is available
-if [ ! -f ${projects_path}/${project}/${application}/${application}.yaml ]
- then
-  echo -e "\n\033[31m[ERROR]   Main application YAML file not found in ${projects_path}\033[0m\n"
-  exit 1
-fi
-
-
-mkdir -p ${deployments}
-ln -sfn ${deployments} ${latest_deployment}
-rsync -av ${projects_path}/${project}/${application}/${application}.yaml ${deployments} > /dev/null
-
-sed -i "s|%{project}|${project}|g" ${deployments}/${application}.yaml
-sed -i "s|%{application}|${application}|g" ${deployments}/${application}.yaml
-sed -i "s|%{environment}|${environment}|g" ${deployments}/${application}.yaml
-
-# replace the variables declared on the cmd
-for xvariable in ${args[@]}
-do
-  variable=$(echo ${xvariable} | { IFS='=' read -a array; echo ${array[0]}; })
-  value=$(echo ${xvariable} | { IFS='=' read -a array; echo ${array[1]}; })
-  sed -i "s|%{${variable}}|${value}|g" ${deployments}/${application}.yaml
-done
-
-# find and replace the rest of the variables with hiera values
-for variable in `grep -o '\%{[a-z,A-Z,0-9,_,-]*\}' ${projects_path}/${project}/${application}/${application}.yaml | sort | uniq | sed 's|[%{}]||g'`
-do
-if [ -z `hiera -c ${custom_hiera} ${variable} project=${project} application=${application} environment=${environment}` ];
-   then
-   echo -e "\n\033[31m${variable} not found in hiera\033[0m\n"
-  exit 1
-  else
-   sed -i "s|%{${variable}}|`hiera -c ${custom_hiera} ${variable} project=${project} application=${application} environment=${environment}`|g" ${deployments}/${application}.yaml
+check_vars() {
+  if [ -z ${project} ]
+  then
+  	usage
+  	exit 1
   fi
-done
+}
 
-cat ${deployments}/${application}.yaml
+set_file() {
+# if project, application and environment or only project and application declared
+  if [[ "${input[@]}" =~ "a" && "${input[@]}" =~ "e" ]] || [[ "${input[@]}" =~ "p" && "${input[@]}" =~ "a" ]]
+  then
+# test if the application is a file or a folder
+    if [ -f ${projects_path}/${project}/${application}.* ]
+    then
+      xfile=${projects_path}/${project}/${application}.*
+      hierarchy="${hrp} ${hra} ${hre}"
+    else
+      xfolder=${projects_path}/${project}/${application}
+      xfile=${xfolder}/*
+      hierarchy="${hrp} ${hra} ${hre}"
+    fi
+# if project and environment or only project declared
+  elif [[ "${input[@]}" =~ "p" && "${input[@]}" =~ "e" ]] || [[ "${input[@]}" =~ "p" ]]
+  then
+    xfile=${projects_path}/${project}.*
+    hierarchy="${hrp} ${hre}"
+  fi
 
-ls -td --group-directories-first ${k8comp_home}/deployments/${project}/${application}-${environment}/${application}-* | tail -n +${deployments_history} | xargs -I % rm -rf %
+# test if either the file or the folder of the application exists
+  for file in ${xfile}
+  do
+    if [ ! -d ${xfolder} ] || [ ! -f ${file} ]
+    then
+      error "${project} ${application} not found in projects folder"
+      exit 1
+    fi
+  done
+}
+
+create_tmp() {
+  tmp_file=$(mktemp /tmp/k8comp.XXXXXX)
+# set the start of the file 
+  for eachfile in ${xfile}
+  do
+    if [ "$(head -1 ${eachfile})" != "---" ]
+    then
+      sed -i '1 i\---' ${eachfile}
+      cat ${eachfile} >> ${tmp_file}
+    else
+      cat ${eachfile} >> ${tmp_file}
+    fi
+  done
+}
+
+replace_var() {
+  sed -i "s|%{project}|${project}|g" ${tmp_file}
+  sed -i "s|%{application}|${application}|g" ${tmp_file}
+  sed -i "s|%{environment}|${environment}|g" ${tmp_file}
+}
+
+replace_xvar() {
+  for xvar in ${args[@]}
+  do
+    sed -i "s|%{${xvar%%=*}}|${xvar##*=}|g" ${tmp_file}
+  done
+}
+
+replace_allvar() {
+  for variable in $(grep -o '\%{[a-z,A-Z,0-9,_,-]*\}' ${tmp_file} |sort |uniq |sed 's|[%{}]||g')
+  do
+    hr=$(hiera -c ${custom_hiera} ${variable} ${hierarchy})
+
+    if [ "${hr}" = "nil" ] || [ "${hr}" = "" ]
+    then
+     error "${variable} not found in hiera"
+     clean
+     exit 1
+    else
+     sed -i "s|%{${variable}}|${hr}|g" ${tmp_file}
+    fi
+  done
+}
+
+print_file() {
+  # set notification variable
+  notification="####### NOTICE ####### Deployment from ${xfile}"
+  # print file on stdout
+  cat ${tmp_file}
+  # echo notification
+  echo ""
+  echo ${notification}
+  echo ""
+}
+
+clean() {
+  if [ -f ${tmp_file} ]
+  then
+    rm -rf ${tmp_file}
+  fi
+}
+
+MAIN
